package fr.univ_amu.iut.backend.magasin;

import fr.univ_amu.iut.backend.entites.*;

/**
 * Classe qui sert à initialiser la liste des champions qui pourront etre presents au magasin
 */
public class InitListeChampionsExistants {
    /**
     * Methode pour initialiser la liste
     */
    public static void InitListe(){
        //Creation Entites
        Mage Alexandre = new Mage ("Alexandre", 88, 30, 41, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Alexandre);
        Combattant Marie = new Combattant ("Marie", 58, 20, 106, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Marie);
        Combattant Thomas = new Combattant ("Thomas", 94, 57, 119, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Thomas);
        Assassin Paul = new Assassin ("Paul", 72, 44, 32, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Paul);
        Assassin Emma = new Assassin ("Emma", 82, 14, 47, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Emma);
        Erudit Florian = new Erudit ("Florian", 18, 26, 75, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Florian);
        Erudit Julien = new Erudit ("Julien", 10, 16, 122, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Julien);
        Mage Lucie = new Mage ("Lucie", 107, 25, 72, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Lucie);
        Yordle Romain = new Yordle ("Romain", 211, 2, 9, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Romain);
        Combattant Camille = new Combattant ("Camille", 135, 63, 137, Rarete.LEGENDAIRE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Camille);
        Assassin Laurent = new Assassin ("Laurent", 145, 1, 47, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Laurent);
        Erudit Alice = new Erudit ("Alice", 46, 14, 130, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Alice);
        Mage Guillaume = new Mage ("Guillaume", 106, 117, 24, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Guillaume);
        Combattant Julie = new Combattant ("Julie", 87, 63, 109, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Julie);
        Mage Maxime = new Mage ("Maxime", 109, 133, 23, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Maxime);
        Yordle Lea = new Yordle ("Lea", 64, 5, 0, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Lea);
        Yordle Nicolas = new Yordle ("Nicolas", 283, 4, 7, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Nicolas);
        Mage Chloe = new Mage ("Chloe", 93, 157, 75, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Chloe);
        Assassin Sebastien = new Assassin ("Sebastien", 103, 19, 36, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Sebastien);
        Combattant Manon = new Combattant ("Manon", 16, 16, 104, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Manon);
        Assassin Benjamin = new Assassin ("Benjamin", 77, 21, 31, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Benjamin);
        Erudit Ines = new Erudit ("Ines", 37, 58, 142, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Ines);
        Yordle Mathieu = new Yordle ("Mathieu", 300, 3, 8, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Mathieu);
        Erudit Clara = new Erudit ("Clara", 20, 11, 136, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Clara);
        Erudit David = new Erudit ("David", 48, 62, 145, Rarete.LEGENDAIRE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(David);
        Yordle Margaux = new Yordle ("Margaux", 404, 1, 3, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Margaux);
        Erudit Vincent = new Erudit ("Vincent", 29, 56, 144, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Vincent);
        Mage Anne = new Mage ("Anne", 53, 52, 40, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Anne);
        Mage Antoine = new Mage ("Antoine", 18, 22, 32, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Antoine);
        Combattant Lola = new Combattant ("Lola", 147, 16, 112, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Lola);
        Combattant Arthur = new Combattant ("Arthur", 82, 74, 116, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Arthur);
        Assassin Oceane = new Assassin ("Oceane", 123, 3, 40, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Oceane);
        Yordle Kevin = new Yordle ("Kevin", 238, 4, 5, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Kevin);
        Assassin Sarah = new Assassin ("Sarah", 112, 8, 50, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Sarah);
        Erudit Raphael = new Erudit ("Raphael", 11, 6, 90, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Raphael);
        Erudit Elise = new Erudit ("Elise", 48, 0, 77, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Elise);
        Erudit Jeremy = new Erudit ("Jeremy", 36, 3, 118, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Jeremy);
        Combattant Charlotte = new Combattant ("Charlotte", 109, 34, 142, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Charlotte);
        Erudit Gauthier = new Erudit ("Gauthier", 31, 63, 134, Rarete.LEGENDAIRE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Gauthier);
        Yordle Melissa = new Yordle ("Melissa", 268, 2, 4, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Melissa);
        Yordle Jonathan = new Yordle ("Jonathan", 24, 7, 10, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Jonathan);
        Yordle Juliette = new Yordle ("Juliette", 430, 3, 2, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Juliette);
        Mage Adrien = new Mage ("Adrien", 30, 92, 20, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Adrien);
        Yordle Lucas = new Yordle ("Lucas", 428, 6, 7, Rarete.LEGENDAIRE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Lucas);
        Assassin Cedric = new Assassin ("Cedric", 98, 56, 38, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Cedric);
        Yordle Amelie = new Yordle ("Amelie", 203, 4, 1, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Amelie);
        Erudit Bastien = new Erudit ("Bastien", 43, 80, 86, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Bastien);
        Combattant Coralie = new Combattant ("Coralie", 120, 17, 142, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Coralie);
        Assassin Tristan = new Assassin ("Tristan", 99, 38, 36, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Tristan);
        Combattant Justine = new Combattant ("Justine", 150, 15, 110, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Justine);
        Combattant Hugo = new Combattant ("Hugo", 142, 2, 130, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Hugo);
        Combattant Eleonore = new Combattant ("Eleonore", 40, 51, 144, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Eleonore);
        Combattant Yann = new Combattant ("Yann", 127, 34, 110, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Yann);
        Assassin Lisa = new Assassin ("Lisa", 87, 28, 44, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Lisa);
        Combattant Simon = new Combattant ("Simon", 72, 56, 137, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Simon);
        Erudit Lilou = new Erudit ("Lilou", 28, 25, 88, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Lilou);
        Erudit Etienne = new Erudit ("Etienne", 30, 50, 131, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Etienne);
        Yordle Maelys = new Yordle ("Maelys", 404, 7, 5, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Maelys);
        Assassin Damien = new Assassin ("Damien", 106, 29, 33, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Damien);
        Erudit Mila = new Erudit ("Mila", 50, 51, 126, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Mila);
        Erudit Fabien = new Erudit ("Fabien", 27, 78, 111, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Fabien);
        Assassin Lina = new Assassin ("Lina", 67, 34, 48, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Lina);
        Mage Alexis = new Mage ("Alexis", 93, 153, 55, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Alexis);
        Erudit Jade = new Erudit ("Jade", 36, 52, 132, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Jade);
        Combattant Maxence = new Combattant ("Maxence", 86, 15, 116, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Maxence);
        Assassin Julia = new Assassin ("Julia", 119, 7, 43, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Julia);
        Erudit Aaron = new Erudit ("Aaron", 28, 5, 102, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Aaron);
        Combattant Estelle = new Combattant ("Estelle", 148, 12, 123, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Estelle);
        Yordle Christopher = new Yordle ("Christopher", 260, 1, 2, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Christopher);
        Erudit Heloise = new Erudit ("Heloise", 32, 12, 92, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Heloise);
        Yordle Steven = new Yordle ("Steven", 150, 1, 7, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Steven);
        Yordle Emilie = new Yordle ("Emilie", 359, 7, 0, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Emilie);
        Assassin Thibault = new Assassin ("Thibault", 100, 18, 46, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Thibault);
        Assassin Jules = new Assassin ("Jules", 119, 38, 50, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Jules);
        Assassin Mailys = new Assassin ("Mailys", 54, 13, 41, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Mailys);
        Mage Gabin = new Mage ("Gabin", 119, 142, 62, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Gabin);
        Erudit Noemie = new Erudit ("Noemie", 30, 20, 88, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Noemie);
        Combattant Clement = new Combattant ("Clement", 96, 2, 111, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Clement);
        Assassin Lilas = new Assassin ("Lilas", 113, 13, 35, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Lilas);
        Assassin Aymeric = new Assassin ("Aymeric", 60, 51, 48, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Aymeric);
        Mage Quentin = new Mage ("Quentin", 35, 56, 44, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Quentin);
        Mage Eva = new Mage ("Eva", 113, 6, 68, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Eva);
        Mage Theo = new Mage ("Theo", 29, 90, 59, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Theo);
        Assassin Lena = new Assassin ("Lena", 134, 8, 46, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Lena);
        Assassin Erwan = new Assassin ("Erwan", 145, 31, 45, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Erwan);
        Combattant Alison = new Combattant ("Alison", 68, 3, 119, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Alison);
        Combattant Sacha = new Combattant ("Sacha", 129, 67, 128, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Sacha);
        Combattant Garance = new Combattant ("Garance", 48, 72, 137, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Garance);
        Combattant Ludovic = new Combattant ("Ludovic", 136, 36, 144, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Ludovic);
        Erudit Hanna = new Erudit ("Hanna", 43, 33, 86, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Hanna);
        Combattant Tyler = new Combattant ("Tyler", 54, 21, 104, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Tyler);
        Mage Clemence = new Mage ("Clemence", 47, 174, 43, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Clemence);
        Erudit Noah = new Erudit ("Noah", 49, 7, 135, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Noah);
        Combattant Victor = new Combattant ("Victor", 148, 40, 139, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Victor);
        Mage Amandine = new Mage ("Amandine", 118, 48, 72, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Amandine);
        Combattant Corentin = new Combattant ("Corentin", 51, 54, 142, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Corentin);
        Combattant Samuel = new Combattant ("Samuel", 79, 5, 138, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Samuel);
        Yordle Margot = new Yordle ("Margot", 387, 10, 6, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Margot);
        Yordle Martin = new Yordle ("Martin", 206, 8, 10, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Martin);
        Mage Louna = new Mage ("Louna", 89, 47, 77, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Louna);
        Assassin Eliott = new Assassin ("Eliott", 84, 25, 41, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Eliott);
        Erudit Romane = new Erudit ("Romane", 14, 34, 137, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Romane);
        Mage Valentin = new Mage ("Valentin", 18, 19, 34, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Valentin);
        Yordle Luna = new Yordle ("Luna", 496, 1, 8, Rarete.LEGENDAIRE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Luna);
        Assassin Jordan = new Assassin ("Jordan", 144, 26, 31, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Jordan);
        Assassin Noa = new Assassin ("Noa", 139, 39, 50, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Noa);
        Mage Leo = new Mage ("Leo", 52, 61, 67, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Leo);
        Erudit Cloe = new Erudit ("Cloe", 17, 14, 86, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Cloe);
        Combattant Gregoire = new Combattant ("Gregoire", 72, 22, 105, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Gregoire);
        Mage Elisa = new Mage ("Elisa", 70, 153, 42, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Elisa);
        Assassin Max = new Assassin ("Max", 145, 0, 38, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Max);
        Yordle Oona = new Yordle ("Oona", 313, 3, 1, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Oona);
        Combattant Edward = new Combattant ("Edward", 144, 39, 111, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Edward);
        Erudit Livia = new Erudit ("Livia", 42, 67, 89, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Livia);
        Mage Evan = new Mage ("Evan", 40, 126, 50, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Evan);
        Erudit Lili = new Erudit ("Lili", 28, 46, 87, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Lili);
        Yordle Timothee = new Yordle ("Timothee", 403, 6, 2, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Timothee);
        Combattant Nina = new Combattant ("Nina", 53, 62, 118, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Nina);
        Assassin Nathan = new Assassin ("Nathan", 119, 31, 43, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Nathan);
        Yordle Maeva = new Yordle ("Maeva", 85, 5, 9, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Maeva);
        Yordle Axel = new Yordle ("Axel", 39, 0, 0, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Axel);
        Combattant Alicia = new Combattant ("Alicia", 34, 25, 106, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Alicia);
        Assassin Alex = new Assassin ("Alex", 92, 49, 31, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Alex);
        Combattant Adele = new Combattant ("Adele", 78, 32, 133, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Adele);
        Mage Marius = new Mage ("Marius", 110, 94, 23, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Marius);
        Mage Aurelie = new Mage ("Aurelie", 59, 85, 67, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Aurelie);
        Erudit Baptiste = new Erudit ("Baptiste", 37, 32, 82, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Baptiste);
        Yordle Leane = new Yordle ("Leane", 172, 5, 0, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Leane);
        Erudit Sylvain = new Erudit ("Sylvain", 17, 41, 84, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Sylvain);
        Assassin Alix = new Assassin ("Alix", 113, 21, 32, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Alix);
        Mage Zozo = new Mage ("Zozo", 81, 169, 32, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Zozo);
        Assassin Enzo = new Assassin ("Enzo", 119, 6, 48, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Enzo);
        Mage Pelvin = new Mage ("Pelvin", 31, 129, 43, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Pelvin);
        Yordle Mohammed = new Yordle ("Mohammed", 189, 2, 4, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Mohammed);
        Assassin PatesAuSucre = new Assassin ("PatesAuSucre", 69, 21, 48, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(PatesAuSucre);
        Erudit Malex = new Erudit ("Malex", 25, 79, 121, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Malex);
        Erudit Lenny = new Erudit ("Lenny", 26, 58, 147, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Lenny);
        Combattant Moktar = new Combattant ("Moktar", 79, 53, 113, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Moktar);
        Erudit Boulette = new Erudit ("Boulette", 22, 14, 142, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Boulette);
        Erudit PatesAuBeurre = new Erudit ("PatesAuBeurre", 17, 30, 103, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(PatesAuBeurre);
        Assassin Pelouse = new Assassin ("Pelouse", 130, 48, 35, Rarete.LEGENDAIRE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Pelouse);
        Erudit Pils = new Erudit ("Pils", 41, 70, 104, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Pils);
        Assassin Fils = new Assassin ("Fils", 114, 51, 35, Rarete.LEGENDAIRE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Fils);
        Mage Kils = new Mage ("Kils", 65, 34, 32, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Kils);
        Erudit Tils = new Erudit ("Tils", 48, 32, 140, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Tils);
        Mage Zils = new Mage ("Zils", 42, 62, 33, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Zils);
        Combattant Sils = new Combattant ("Sils", 126, 61, 143, Rarete.LEGENDAIRE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Sils);
        Mage Mils = new Mage ("Mils", 92, 176, 41, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Mils);
        Assassin Gils = new Assassin ("Gils", 134, 45, 41, Rarete.LEGENDAIRE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Gils);
        Erudit Wils = new Erudit ("Wils", 11, 10, 137, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Wils);
        Combattant Xils = new Combattant ("Xils", 131, 42, 150, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Xils);
        Combattant Cils = new Combattant ("Cils", 71, 64, 123, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Cils);
        Erudit Ragnar = new Erudit ("Ragnar", 49, 57, 128, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Ragnar);
        Erudit Fredo = new Erudit ("Fredo", 21, 28, 76, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Fredo);
        Erudit Fredos = new Erudit ("Fredos", 34, 68, 150, Rarete.LEGENDAIRE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Fredos);
        Yordle Momox = new Yordle ("Momox", 336, 6, 10, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Momox);
        Yordle DjibSan = new Yordle ("DjibSan", 338, 9, 7, Rarete.RARE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(DjibSan);
        Erudit Shori = new Erudit ("Shori", 29, 19, 91, Rarete.COMMUN);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Shori);
        Erudit Fred = new Erudit ("Fred", 39, 75, 150, Rarete.LEGENDAIRE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Fred);
        Combattant Luca = new Combattant ("Luca", 150, 64, 125, Rarete.LEGENDAIRE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Luca);
        Assassin Nils = new Assassin ("Nils", 150, 40, 50, Rarete.LEGENDAIRE);
        ApprovisionnementMagasin.ajouterALaListeDesChampionsExistants(Nils);
    }
}
